# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/boards/arm/*/*.dtsi'
      - .github/workflows/draw-keymaps.yml


jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: 'config/*.keymap'
      output_folder: keymap-drawer
      amend_commit: true
      parse_args: '-c 12'
      draw_args: '-o "{split: true, rows: 3, columns: 6, thumbs: 4}"'
